### ISSUE TITLE
Change background color to navy

### ISSUE THREAD

**Issue by ilyasotkov** [ilyasotkov/concourse-pipelines#1]
> [This issue is used for CI testing]

I think we should change background color in the app to **navy**.

**Comment by ilyasotkov** [comment]
😱 Oops, this issue was meant for https://github.com/ilyasotkov/rails-react-boilerplate.

Closing this.

**Comment by bacle** [comment]
did you just talk to yourself?

**Comment by ilyasotkov** [comment]
@bacle I sure did. I call this "documenting in a conversational style" 😀
